on:
  create:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v6
    - name: build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.3.1
        target: esp32
        command: idf.py build
    - name: merge-bin
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.3.1
        target: esp32
        command: idf.py merge-bin
    - name: ls
      run: ls -hl build
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: merged-binary.bin
        path: build/merged-binary.bin
